### ISSUE TITLE
aiuto con errore

### ISSUE THREAD

**Issue by pablolive1** [simonemastella/SureBetFinder#1]
Ciao. Puoi aiutarmi con questo? l'errore: OpenSSL.SSL.Error: [('SSL routine', 'tls_process_server_certificate', 'verifica certificato fallita')], il tuo lavoro è fantastico

**Comment by simonemastella** [comment]
Grazie.
La versione presente è deprecata...  Incorrerai in altri errori non fixati in questa repo proprio per scoraggiare l'utilizzo 
Quell'errore potrebbe essere causato dalle dipendenze di **requests_html**
